### ISSUE TITLE
ipfs config edit

### ISSUE THREAD

**Issue by NatoBoram** [elopio/ipfs-snap#16]
`ipfs config edit` seems impossible to use because of snap's limitations.

```bash
EDITOR=/bin/nano

ipfs config edit
sh: 1: /bin/nano: not found
Error: exit status 127
```

A workaround would be to use `$EDITOR $IPFS_PATH/config` instead of `ipfs config edit`, but that's long to type and I don't want to have to remember that command. Any other idea?

**Comment by come-maiz** [comment]
This is by design in snaps.
I guess the solution would be to add an interface to the snap that allows it to launch whatever binary is in `$EDITOR`. The place to talk about this is https://forum.snapcraft.io

Thanks for your report @NatoBoram.
