### ISSUE TITLE
Update to v0.4.23

### ISSUE THREAD

**Issue by DavidBurela** [elopio/ipfs-snap#19]
Version 0.4.23 was released 2 weeks ago.
It has critical bug fixes before v0.5.0 is released
https://github.com/ipfs/go-ipfs/releases/tag/v0.4.23

**Comment by olizilla** [comment]
0.6 is now released to stable. I've adopted this, and it lives on at https://github.com/ipfs-shipyard/ipfs-snap and https://github.com/ipfs/go-ipfs/pull/7529

**Comment by DavidBurela** [comment]
great, I'll close this
