### ISSUE TITLE
Unable to add files that are outside of the snap confinement

### ISSUE THREAD

**Issue by colinl** [elopio/ipfs-snap#4]
It is not possible to, for example 
ipfs add ~/somefile
as the file is not accessible from the snap. A permission denied error is seen.

It would make sense to allow access to files in the users home directory structure.

**Comment by come-maiz** [comment]
Thanks @colinl!

**Comment by xloem** [comment]
I notice ipfs-desktop got removable-media, but I still can't use a removable-media IPFS_PATH on the plain ipfs snap.  Might still need an update.

Since ipfs has a system-wide daemon, it would be ideal to have access to some system-wide folder.
