### ISSUE TITLE
IPFS snap not found

### ISSUE THREAD

**Issue by Bugsbane** [elopio/ipfs-snap#7]
Hi there,
I'm sure this is probably something super basic and obvious, but this is my first time trying a snap, but I came across your blog post "Crowdtesting with the Ubuntu community: the case of IPFS" and thought I'd give it a try. When I run sudo snap install ipfs on my Kubuntu 16.10 machine though, I just get the error:

> error: cannot install "ipfs": snap not found

...and I'm not sure why. Is there a snap equivalent of apt-get update I need to run first?

> sudo snap install hello-world

...works just fine though.

Currently, I'm trying to drum up support in the Nextcloud community for adding IPFS to Nextcloud as an external storage source, so users can have their data backed up in a distributed, remote fashion (and add a ton of IPFS nodes around the world at the same time ;P )

**Comment by come-maiz** [comment]
Hello @Bugsbane,

I like the nextcloud idea very much. About your problem, I have no idea. This is what I see:

$ snap find ipfs
Name  Version  Developer  Notes  Summary
ipfs  v0.4.7   elopio     -      global, versioned, peer-to-peer filesystem

Can you please tell me more about your system?

**Comment by mkg20001** [comment]
Try it on an non amd64 device.
It will fail as there is no version for that architecture (like armhf)

**Comment by come-maiz** [comment]
@mkg20001 ah, right. I have only published the amd64 version. @Bugsbane are you in a different arch?

Travis only lets me build for amd64.
I'm waiting for this bug to be solved, to be able to use the snapcraft.io builders for multiple architectures: https://github.com/canonical-ols/build.snapcraft.io/issues/527

**Comment by Bugsbane** [comment]
I don't remember which machine I was using unfortunately. My main desktop is amd64, but my laptop is Intel. Is try on both, but unfortunately my main machine just started having hardware problems that are doing it from booting. When it's up again, I'll give it a try.

**Comment by come-maiz** [comment]
We are now building and releasing for amd64, armhf and arm64. I'm closing this one.
Thanks for the report.

**Comment by Bugsbane** [comment]
For the record, it's working fine now on my (amd64) main machine. Thanks!

**Comment by come-maiz** [comment]
good to know @Bugsbane. I've recently moved 0.4.14 to candidate. Would you help us testing it?

    sudo snap referesh ipfs --candidate

**Comment by Bugsbane** [comment]
What specifically would you like my help to test? Just the upgrade, or general usage? The upgrade worked fine, btw...

**Comment by come-maiz** [comment]
@Bugsbane just use it as you normally would, to see if you find something weird. Thanks!
